resources:
- name: hello_concourse
  type: git
  source:
    uri: https://github.com/kejadlen/hello_concourse
    branch: master
- name: cf
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: {{cf-username}}
    password: {{cf-password}}
    organization: seattle-beach
    space: hello_concourse
- name: s3
  type: s3
  source:
    bucket: hello-concourse
    regexp: hello.tar.gz
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}
    region_name: us-west-2

jobs:
- name: app-test
  plan:
  - get: hello_concourse
    trigger: true
  - task: app-test
    config:
      platform: linux
      image: docker:///ruby
      inputs:
        - name: hello_concourse
      run:
        path: ruby
        args:
          - hello_concourse/services/app.rb
- name: hello-build
  plan:
  - get: hello_concourse
    trigger: true
  - task: hello-build
    config:
      platform: linux
      image: docker:///golang
      inputs:
        - name: hello_concourse
      run:
        path: go
        args:
          - build
          - -o
          - hello_concourse/services/hello/build/hello
          - hello_concourse/services/hello/hello.go
      outputs:
        - name: hello-build
          path: hello_concourse/services/hello/build
  - task: hello-tar
    config:
      platform: linux
      image: docker:///golang
      inputs:
        - name: hello-build
      run:
        path: tar
        args:
          - czf
          - hello-build/hello.tar.gz
          - hello-build/hello
      outputs:
        - name: hello-tar
          path: hello-build
  - put: s3
    params:
      file: hello-tar/hello.tar.gz
- name: hello-test
  plan:
  - get: hello_concourse
    trigger: true
    passed:
      - hello-build
  - task: hello-test
    config:
      platform: linux
      image: docker:///golang
      inputs:
        - name: hello_concourse
      run:
        path: go
        args:
          - test
          - -v
          - hello_concourse/services/hello/hello_test.go
          - hello_concourse/services/hello/hello.go
- name: hello-deploy
  plan:
  - get: hello_concourse
    trigger: true
    passed:
      - hello-test
  - get: s3
    trigger: true
    passed:
      - hello-build
  - task: hello-untar
    config:
      platform: linux
      image: docker:///golang
      inputs:
        - name: s3
      run:
        path: tar
        args:
          - xzf
          - s3/hello.tar.gz
          - -C
          - s3
      outputs:
        - name: hello-untar
          path: s3
  - put: cf
    params:
      manifest: hello_concourse/services/hello/manifest.yml
      path: hello-untar
- name: world-test
  plan:
  - get: hello_concourse
    trigger: true
  - task: world-test
    config:
      platform: linux
      image: docker:///ruby
      inputs:
        - name: hello_concourse
      run:
        path: ruby
        args: 
          - hello_concourse/services/world.rb
